<style>
/*.more-views ul li{width:80px;float:left;border: solid 1px #ddd;margin: 5px;}
.more-views ul li img{margin:0 auto;padding: 2px;}
.left-img{position: relative; top: 21px; left: 0;}   
.right-img{position: absolute; top: 21px; right: 0;}   
.nav-control{position: absolute;width:50%;}
*/
</style>


<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
	
?>
<?php $imageheight	= 	Mage::getStoreConfig('imagezoom/imagesetting/imageheight');
//var_dump($imageheight);
?>
<?php $imagewidth	=	 Mage::getStoreConfig('imagezoom/imagesetting/imagewidth');?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image">
    <?php
        $_img = '<img id="image1" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageheight,$imagewidth).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<p class="zoom-notice" id="track_hint"><?php echo $this->__('Mouse over the image for zoom') ?></p>


<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imageheight,$imagewidth).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" id="image1" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
 <script type="text/javascript" src="<?php echo $this->getSkinUrl('Fourtek/js/jquery.bxslider.js', array('_secure'=>true));?>"></script>
  <script type="text/javascript" src="<?php echo $this->getSkinUrl('Fourtek/js/jquery.bxslider.min.js', array('_secure'=>true));?>"></script>
  <link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/css/Fourtek/jquery.bxslider.css" type="text/css" />
<?php if (count($this->getGalleryImages()) > 3): ?>
	 <script>
    $j = jQuery.noConflict();
    $j(document).ready(function(){
    $j('.bxslider-media').bxSlider({
       infiniteLoop: false,
        minSlides: 3,
        maxSlides: 4,
        slideWidth: 79,
        slideMargin: 10
    });
    });
        
 </script> 
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>

    <ul class="product-image-thumbs bxslider-media"> 

    <?php foreach ($this->getGalleryImages() as $_image): ?>
	
        <li>
            <a onclick="imageswitcher('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile());?>','<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($imageheight,$imagewidth);?>');" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>

    </ul>


       
</div>

	<?php endif; ?>
	
<!--<style type="text/css">
.magnifyarea{ /* CSS to add shadow to magnified image. Optional */
    box-shadow: 5px 5px 7px #818181;
    -webkit-box-shadow: 5px 5px 7px #818181;
    -moz-box-shadow: 5px 5px 7px #818181;
    filter: progid:DXImageTransform.Microsoft.dropShadow(color=#818181, offX=5, offY=5, positive=true);
    background: white;
}
</style>-->


<script type="text/javascript">

function imageswitcher(imagename, imagefull){	
	//var newImg	=	imagename.src;
	//imagezoom_configurations_zoomheight
	jQuery('#image1').attr('src',imagefull);
	var options	=	{
		zoomrange: [<?php echo "2";?>, <?php echo '20';?>],
		magnifiersize: [<?php echo Mage::getStoreConfig('imagezoom/configurations/zoomwidth');?>,<?php echo Mage::getStoreConfig('imagezoom/configurations/zoomheight');?>],
		magnifierpos: 'right',
		cursorshade: true,
		largeimage: imagename //<-- No comma after last option!
	}
		jQuery('#image1').addimagezoom(options);
}
</script>
<script type="text/javascript">
//<![CDATA[
    Event.observe(window, 'load', function() {
        jQuery('#image1').addimagezoom({	
		zoomrange: [<?php echo "2";?>, <?php echo '20';?>],
		magnifiersize: [<?php echo Mage::getStoreConfig('imagezoom/configurations/zoomwidth');?>,<?php echo Mage::getStoreConfig('imagezoom/configurations/zoomheight');?>],
		magnifierpos: '<?php echo 'right';?>',
		cursorshade: true,		
		largeimage: '<?php echo $this->helper('catalog/image')->init($_product, 'image');?>' //<-- No comma after last option!
	})
	featuredimagezoomer.loadinggif='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'VS/spinningred.gif'; ?>';
	featuredimagezoomer.mousewheeltext="<?php echo $this->__('Use Mouse Wheel to Zoom In/Out'); ?>";
	featuredimagezoomer.curzoom="<?php echo $this->__('Current Zoom'); ?>";
    });
//]]>
</script>
